version: 0.0
os: linux


files:
  - source: /
    destination: home/ec2-user/flask-app

hooks:
  AfterInstall:
    - location: script/install_dependencies.sh
       timeout: 300
       runas: root
       

  ApplicationStart:
    - location: script/start_container.sh
      timeout: 300
      runas: root

