version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11

  pre_build:
    commands:
      - echo "Installing dependencies..."
      - chmod +x script/install_dependencies.sh
      - ./script/install_dependencies.sh

  build:
    commands:
      - echo "Running build phase..."
      - pwd
      - ls -ltr
      - echo "Build completed"

  post_build:
    commands:
      - echo "Build completed successfully"

artifacts:
  files:
    - '**/*'
