version: 0.2

env:
  parameter-store:

phases:
  install:
    runtime-version:
      python: 3.11

  pre_build:
    commands:
      - echo "Install dependencies..."
      - pip install -r python-flask-cicd-deploy/script/install_dependencies.sh
      

    build:
      cpmmands:
        - echo "Running tests....."
        - cd python-flask-cicd-deploy/
        - echo "Build Docker image......"

  post_build:
    commands:
      - echo "Build completed successfuly"


artifacts:
  files:
    - '**/*'
